### ISSUE TITLE
ERICSSON - MEAS_COLLEC_XML - parsing output empty - Cloud oriented 

### ISSUE THREAD

**Issue by jsanz01** [bodastage/bts-ce-lite#173]
Hi,
I've installed BTS-CE-Lite in my computer and tried to use it to Parse and Import an PM File from an OpenStack (type of) cloud system. It implements the MEAS_COLLECT_XML format.
Attached a small example.
No error is shown but resulting file is empty.
Is this use case supported in bts-ce-lite?

Thanks in advance, Jose
[PRODUCTION_ECMES_20190926_0945-1000_metrics.zip](https://github.com/bodastage/bts-ce-lite/files/4328210/PRODUCTION_ECMES_20190926_0945-1000_metrics.zip)

**Comment by erssebaggala** [comment]
@jsanz01 it should be but let me the sample you have shared and confirm

**Comment by erssebaggala** [comment]
@jsanz01 we are not handling this format measurement collect format well. We will release update over the weekend for this.

**Comment by jsanz01** [comment]
@erssebaggala Do you have any news about this point?. I could be really great to use Boda Stage with these files. Please, let me know if I can support. Thanks, Jose

**Comment by erssebaggala** [comment]
@jsanz01 changes to the  measurement collection parser have been made at https://github.com/bodastage/boda-measdatacollectionparser/releases .  It will be updated in today's release.

**Comment by jsanz01** [comment]
@erssebaggala Hi Emmanuel, now that the new measdatacollectionparser has been improved with the new type of "r" fields. 
Could you please let me know when this new library (.jar) file will be included in the bts-ce-lite application (.EXE package rebuild)?
Thanks, Jose

**Comment by erssebaggala** [comment]
@jsanz01, give me a day to update it

**Comment by erssebaggala** [comment]
@jsanz01 the parser has been updated check ot
https://github.com/bodastage/bts-ce-lite/releases/tag/v0.5.0. Thanks for reporting this issue.
