### ISSUE TITLE
typeorm throws error:  (DriverPackageNotInstalledError): SQLite package has not been found installed

### ISSUE THREAD

**Issue by erssebaggala** [bodastage/bts-ce-lite#2]
**System**
Windows 10
node@v10.15.3
npm@6.4.1
electron@4.1.5

Typeorm throws error above when using sqlite3.

Similar to:
https://github.com/typeorm/typeorm/issues/2456

**Comment by timoschwarzer** [comment]
@erssebaggala Randomly found your issue. If it works if you downgrade TypeORM to 0.2.13 then this issue might be interesting for you: https://github.com/typeorm/typeorm/issues/4210

**Comment by erssebaggala** [comment]
@timoschwarzer thanks. I will test and confirm.

**Comment by erssebaggala** [comment]
@timoschwarzer I tested and ran into a bunch of other 
First, I got this:
`Module not found: Can't resolve 'aws-sdk' in 'C:\Users\Emmanuel\Documents\Bodastage\code_repos\pr\bts-ce-lite\node_modules\node-pre-gyp\lib'`

I bit and installed it. Then I got this error:
Module not found: Can't resolve 'aws-sdk' in 
```
./node_modules/npm/bin/npm-cli.js 1:0
Module parse failed: Unexpected character '#' (1:0)
```
I will investigate further and share my findings

**Comment by timoschwarzer** [comment]
These two errors don't seem related to TypeORM though

**Comment by erssebaggala** [comment]
typeorm has no clear way of switching schemas for PostgreSQL at the moment. We have decided to use node-pg-migrate
