### ISSUE TITLE
Process CM Dumps been running for almost 9 hours (..parsing Huawei NBIExport_XML files)

### ISSUE THREAD

**Issue by alfonseo** [bodastage/bts-ce-lite#70]
**Boda-Lite Version**: 0.2.3

Process CM dump has been running for almost 9 hours trying to parse Huawei NBIExport_XML files

[log.log](https://github.com/bodastage/bts-ce-lite/files/3420759/log.log)
![Snapshot](https://user-images.githubusercontent.com/40150003/61691958-02958e00-ad2d-11e9-9579-9418ad6438ac.png)

**Comment by muralithiyagarajan** [comment]
from your log file, Parsing not started. Confirm java command is available in the system PATH i.e. can be run from the terminal. Type java in the terminal to confirm

**Comment by alfonseo** [comment]
Issue resolved after updating java environment path variable. Thank you.

**Comment by erssebaggala** [comment]
@alfonseo and @muralithiyagarajan let's keep this open until it's fixed with an appropriate error in the next release.

**Comment by erssebaggala** [comment]
Fixed in release 0.3.1
